# Generated by Django 5.0.6 on 2024-07-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(default='', max_length=50)),
                ('talla', models.CharField(default='Null', max_length=10)),
                ('color', models.CharField(default='Null', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.BooleanField(default=True)),
                ('genero', models.CharField(default='Null', max_length=10)),
            ],
        ),
    ]
