# Generated by Django 5.0.6 on 2024-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(default='hombre', max_length=10),
        ),
    ]
